import type { ColumnDef, CellStyle, InvoiceTemplate, MetadataRow, TotalRowConfig } from "@/utils/invoice-template-export";

export const AVAILABLE_FIELDS: { value: string; label: string }[] = [
  { value: "row_number", label: "No. (Row Number)" },
  { value: "orderCode", label: "Order Code" },
  { value: "shipmentCode", label: "Shipment Code" },
  { value: "freightOrder", label: "Freight Order" },
  { value: "dispatchDate", label: "Dispatch Date" },
  { value: "route.origin", label: "Origin" },
  { value: "route.destination", label: "Destination" },
  { value: "routeName", label: "Route Name (Origin - Destination)" },
  { value: "route.routeCode", label: "Route Code" },
  { value: "order.allocationNumber", label: "Allocation Number" },
  { value: "order.totalRequest", label: "Quantity" },
  { value: "order.unitOfMeasurement", label: "Unit of Measurement" },
  { value: "order.numberOfVehicles", label: "Number of Vehicles" },
  { value: "order.agent.agentCode", label: "Agent Code / Distributor No." },
  { value: "order.agent.name", label: "Agent / Distributor Name" },
  { value: "order.packaging.name", label: "Packaging / Material Type" },
  { value: "commodity", label: "Commodity / Material" },
  { value: "vehicleTypeName", label: "Truck / Vehicle Type" },
  { value: "vehicleOwnership", label: "Vehicle Ownership" },
  { value: "vehicle.plateNumber", label: "Plate Number" },
  { value: "vehicle.trailerPlate", label: "Trailer Plate" },
  { value: "driver", label: "Driver Name" },
  { value: "tripType", label: "Trip Type" },
  { value: "pricingType.amount", label: "Rate / Unit Price" },
  { value: "dispatchWeight", label: "Dispatch Weight" },
  { value: "odometerAtDispatch", label: "Odometer at Dispatch" },
  { value: "odometerAtComplete", label: "Odometer at Complete" },
  { value: "shipperIssueVoucher", label: "Shipper Issue Voucher / Original Doc" },
  { value: "shipperReceiveVoucher", label: "Shipper Receive Voucher / For Doc No." },
  { value: "agentReceiveVoucher", label: "GRN / Agent Receive Voucher" },
  { value: "agentIssueVoucher", label: "Agent Issue Voucher" },
  { value: "totalPrice", label: "Total Price / Payment Amount" },
  { value: "returnQty", label: "Return Qty" },
  { value: "remark", label: "Remark" },
  // Status timestamps
  { value: "statusTime.vehicleAssignedTime", label: "Time: Vehicle Assigned" },
  { value: "statusTime.acceptedTime", label: "Time: Accepted" },
  { value: "statusTime.waitingToLoadAtOriginTime", label: "Time: Arrived at Origin" },
  { value: "statusTime.loadingStartedAtOriginTime", label: "Time: Loading Started" },
  { value: "statusTime.loadedAtOriginTime", label: "Time: Loaded at Origin" },
  { value: "statusTime.departedTime", label: "Time: Departed" },
  { value: "statusTime.enRouteToDestinationTime", label: "Time: En Route to Destination" },
  { value: "statusTime.arrivedAtDestinationTime", label: "Time: Arrived at Destination" },
  { value: "statusTime.waitingToOffloadAtDestinationTime", label: "Time: Waiting to Offload" },
  { value: "statusTime.offloadingStartedAtDestinationTime", label: "Time: Offloading Started" },
  { value: "statusTime.offloadedAtDestinationTime", label: "Time: Offloaded at Destination" },
  { value: "statusTime.waitingToLoadAtDestinationTime", label: "Time: Waiting to Load at Dest." },
  { value: "statusTime.loadedAtDestinationTime", label: "Time: Loaded at Destination" },
  { value: "statusTime.enRouteToOriginTime", label: "Time: En Route to Origin" },
  { value: "statusTime.arrivedAtOriginTime", label: "Time: Arrived at Origin (Return)" },
  { value: "statusTime.offloadedAtOriginTime", label: "Time: Offloaded at Origin" },
  { value: "statusTime.completedTime", label: "Time: Completed" },
  { value: "static", label: "Static Text" },
];

export const FIELD_DEFAULT_TYPE: Record<string, ColumnDef["type"]> = {
  row_number: "number",
  dispatchDate: "date",
  "order.totalRequest": "number",
  "order.numberOfVehicles": "number",
  "pricingType.amount": "number",
  totalPrice: "currency",
  dispatchWeight: "number",
  odometerAtDispatch: "number",
  odometerAtComplete: "number",
  returnQty: "number",
  static: "static",
  "statusTime.vehicleAssignedTime": "date",
  "statusTime.acceptedTime": "date",
  "statusTime.waitingToLoadAtOriginTime": "date",
  "statusTime.loadingStartedAtOriginTime": "date",
  "statusTime.loadedAtOriginTime": "date",
  "statusTime.departedTime": "date",
  "statusTime.enRouteToDestinationTime": "date",
  "statusTime.arrivedAtDestinationTime": "date",
  "statusTime.waitingToOffloadAtDestinationTime": "date",
  "statusTime.offloadingStartedAtDestinationTime": "date",
  "statusTime.offloadedAtDestinationTime": "date",
  "statusTime.waitingToLoadAtDestinationTime": "date",
  "statusTime.loadedAtDestinationTime": "date",
  "statusTime.enRouteToOriginTime": "date",
  "statusTime.arrivedAtOriginTime": "date",
  "statusTime.offloadedAtOriginTime": "date",
  "statusTime.completedTime": "date",
};

export function makeDefaultTemplate(): InvoiceTemplate {
  return {
    name: "",
    ownerId: "",
    ownerType: "shipper",
    productType: "IN_BOUND",
    titleRow: { enabled: false, text: "", style: { bold: true, fontSize: 14, align: "center", bgColor: "FFFFFF" } },
    metadataRows: [
      { id: "meta_1", labelText: "Transporter Name", valueSource: "transporterName", enabled: true, colspanLabel: 3, colspanValue: 0 },
      { id: "meta_2", labelText: "REQUESTING MONTH", valueSource: "month", enabled: true, colspanLabel: 3, colspanValue: 0 },
      { id: "meta_3", labelText: "INVOICE NO", valueSource: "invoiceNo", enabled: true, colspanLabel: 3, colspanValue: 0 },
      { id: "meta_4", labelText: "PO Number", valueSource: "poNumber", enabled: true, colspanLabel: 3, colspanValue: 0 },
    ] as MetadataRow[],
    columns: [
      { id: "col_no", field: "row_number", label: "No", width: 6, type: "number" },
      { id: "col_date", field: "dispatchDate", label: "Date", width: 14, type: "date" },
      { id: "col_origin", field: "route.origin", label: "Origin", width: 16, type: "text" },
      { id: "col_destination", field: "route.destination", label: "Destination", width: 16, type: "text" },
      { id: "col_plate", field: "vehicle.plateNumber", label: "Truck Plate", width: 14, type: "text" },
      { id: "col_driver", field: "driver", label: "Driver Name", width: 20, type: "text" },
      { id: "col_qty", field: "order.totalRequest", label: "QTY", width: 10, type: "number" },
      { id: "col_price", field: "totalPrice", label: "Payment Amount", width: 16, type: "currency" },
    ],
    styles: {
      header: { bold: true, color: "FFFFFF", bgColor: "1565C0", align: "center", wrapText: true, border: true },
      dataRow: { border: true, align: "left" },
      alternateRow: { bgColor: "F5F5F5", border: true },
      totalRow: { bold: true, bgColor: "E8E8E8", border: true },
    },
    totalRows: [
      { id: "total_1", label: "TOTAL", columns: ["totalPrice"] } as TotalRowConfig,
    ],
  };
}
